# Generated by Django 3.1.1 on 2020-09-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0002_auto_20200929_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='Abfrage',
            new_name='query',
        ),
    ]
