# Generated by Django 3.1.1 on 2020-10-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0003_auto_20200929_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='table',
            field=models.CharField(choices=[('auth_user', 'User'), ('likes_table', 'Likes'), ('posts_table', 'Posts'), ('comments_table', 'Comments')], default=('auth_user', 'User'), max_length=50),
        ),
    ]
