# Generated by Django 3.1.1 on 2020-10-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20201008_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
