# Generated by Django 3.1.1 on 2020-10-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20201010_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(default='profile/blank-profile-picture.png', upload_to='profile/'),
        ),
    ]
