# Generated by Django 3.1.1 on 2020-11-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_user_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='following',
        ),
    ]
