# Generated by Django 3.1.1 on 2020-11-17 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0009_remove_user_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='followers',
            field=models.ManyToManyField(related_name='is_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
